const TYPES = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  CLEAR_USER: 'CLEAR_USER',
  SIGN_UP_ACCOUNT : 'SIGN_UP_ACCOUNT',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  PAYMENT: 'PAYMENT',
  PURCHASE_ORDER: 'PURCHASE_ORDER'
}

export {TYPES};