$(document).ready(function(){
    $("#toggle-menu").click(function(){
        $("#main-menu").css({
            "display":"block",
            "position":"absolute",
            "background":"white",
            "top":0,
            "left":0,
            "z-index":1
        })
    })
    $(".btn-hide").click(function(){
        $("#main-menu").css({
            "display":"none"
        })
    })
});