$(document).ready(function(){
    $("#toggle-menu").click(function(){
        $("#main-menu").css({
            "display":"block",
            "position":"fixed",
            "height":"100%",
            "background":"white",
            "top":0,
            "left":0,
            "z-index":1
        })
        $("#black-screen").css({
            "display":"block"
        })
    })
    $(".btn-hide").click(function(){
        $("#main-menu").css({
            "display":"none"
        })
    })
});